server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/


spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      label: master #配置仓库分支
      server:
        git:
          uri: https://github.com/Dlrb5520/springconfig # 配置git仓库地址
          username: Dlrb5520  #git登录用户名
          password: xuanjun123. #git登录密码
          search-paths: springconfig #检索路径

